name: restaurante
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: 'Darker Grotesque'
      fonts:
        - asset: fonts/Darker_Grotesque/DarkerGrotesque-Black.ttf
        - asset: fonts/Darker_Grotesque/DarkerGrotesque-Bold.ttf
        - asset: fonts/Darker_Grotesque/DarkerGrotesque-ExtraBold.ttf
        - asset: fonts/Darker_Grotesque/DarkerGrotesque-Light.ttf
        - asset: fonts/Darker_Grotesque/DarkerGrotesque-Medium.ttf
        - asset: fonts/Darker_Grotesque/DarkerGrotesque-Regular.ttf
        - asset: fonts/Darker_Grotesque/DarkerGrotesque-SemiBold.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
